### ISSUE TITLE
Publish to elm-package

### ISSUE THREAD

**Issue by antoinerey** [abadi199/elm-horizon#3]
I arrived here looking for an Elm package managing the Horizon library. After reading the doc, I have to say I'm not disapointed at all. I ran your exemples, but I can't find your package on [package.elm-lang.org](http://package.elm-lang.org). 

I understand that your library is not ready yet, according your disclaimer in the readme. But, could you still publish a (beta?) version to the package manager ? This way, people could easily try this library, and contribute if they can/need to.

I'd be glad to help you build a great library around Horizon but I can't find a way to try this library into my own projects. 

---

**EDIT**: I'm confused, I'm still learning Elm. It seems that package including ports can't be plublished to the official package hub. So, how packages like this one can be shared and installed ? Should I manually copy and paste your source code into my own application ? It sounds crazy.

**Comment by abadi199** [comment]
You're right. There's no easy way to publish this package into elm-package because of ports, because people need to include the js file into their project somehow manually. The best thing we can do is extract some of the core functions into its own module separate from the ports module, and publish those core module with an instruction on how to use it.
I have some ideas in my head on how to do this, but honestly, I don't really have spare time to do this at the moment. Feel free to fork this question and try to do something like that.
